# Generated by Django 5.0.6 on 2024-05-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0002_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
