# Generated by Django 5.0.6 on 2024-05-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Username must be 255 characters or fewer.', 'unique': 'A user with that username already exists.'}, help_text='Required. 255 characters or fewer. Only Alphanumeric characters', max_length=255, unique=True, verbose_name='username'),
        ),
    ]
