# Generated by Django 5.0.6 on 2024-06-03 22:52

import django.utils.timezone
import userRegistration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0006_remove_userprofile_status_userprofile_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='userRegistration.adminpermission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'admin group',
                'verbose_name_plural': 'admin groups',
            },
            managers=[
                ('objects', userRegistration.models.AdminGroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'max_length': 'Username must be 255 characters or fewer.', 'unique': 'A user with that username already exists.'}, help_text='Required. 255 characters or fewer. Only Alphanumeric characters', max_length=255, unique=True, verbose_name='username')),
                ('first_name', models.CharField(error_messages={'blank': 'This field cannot be blank. First name is required'}, max_length=150, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(error_messages={'blank': 'This field cannot be blank. Last name is required'}, max_length=150, null=True, verbose_name='last_name')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_admin', models.BooleanField(default=True, help_text='Designates that this user has all permissionswithout explicitly assigning them')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='This user belongs to the admin group. See group for user permissions', related_name='admin_user', related_query_name='admin', to='userRegistration.admingroup', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', userRegistration.models.AdminManager()),
            ],
        ),
    ]
