# Generated by Django 5.0.6 on 2024-06-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0007_adminpermission_admingroup_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='user@email.com', error_messages={'blank': 'Email cannot be left blank.', 'max_length': 'Email must be 225 characters or fewer.', 'unique': 'Email address must be unique. Another user exists with this email address.'}, help_text='Email is required and must be 225 characters or fewer.', max_length=225, unique=True, verbose_name='email'),
        ),
    ]
