# Generated by Django 5.0.6 on 2024-06-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0009_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='user@email.com', error_messages={'blank': 'Email cannot be left blank.', 'max_length': 'Email must be 225 characters or fewer.', 'unique': 'Email address must be unique. Another user exists with this email address.'}, help_text='Email is required and must be 225 characters or fewer.', max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank. First name is required'}, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'This field cannot be blank. Last name is required'}, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Username must be 255 characters or fewer.', 'unique': 'A user with that username already exists.'}, help_text='Required. 255 characters or fewer. Only Alphanumeric characters', unique=True, verbose_name='username'),
        ),
    ]
